#define LOCAL_SERVER_ADDRESS "127.0.0.1"
#define LOCAL_SERVER_PORT 8080

#define INET_SERVER_ADDRESS "0.0.0.0"
#define INET_SERVER_PORT "0.0.0.0"

#define USE_LOCAL_SERVER 1
#define USE_CLASS_PRINT 1
#define USE_PACKET_PRINT 1
